<?php

echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">' . "\r\n" . '<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">' . "\r\n" . '<head>' . "\r\n" . '	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">' . "\r\n" . '	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>' . "\r\n" . '	<title>详情页</title>' . "\r\n" . '	<script type="text/javascript" src="js/jquery.min.js"></script>' . "\r\n" . '	<script type="text/javascript" src="js/laydate/laydate.js"></script>' . "\r\n" . '	<script type="text/javascript" src="js/layer/layer.js"></script>' . "\r\n" . '	<script type="text/javascript" src="js/global.js"></script>' . "\r\n" . '	<link rel="stylesheet" type="text/css" href="css/reset.css" />' . "\r\n" . '	<link rel="stylesheet" type="text/css" href="css/global.css" />' . "\r\n" . '	<style type="text/css">' . "\r\n" . '	.iframe_top{background: url("./images/iframe_top01.png") 0 0 no-repeat;width:946px;height: 42px;position: relative;font-size: 15px;color: #fff;line-height: 42px;}' . "\r\n" . '	.iframe_body{background: url("./images/iframe_body.png") 0 0 repeat-y;overflow: hidden;padding-left:10px;padding-top:5px;padding-bottom: 0;width:946px;}' . "\r\n" . '	.iframe_foot{background: url("./images/iframe_foot.png") 0 0 no-repeat;width: 946px;height: 18px;}' . "\r\n" . '	.layer_iframe .close{top:13px;right: 15px;}' . "\r\n" . '	.close{font-size: 20px;font-weight: bold;color: #fff;position: absolute;right: 25px;top:22px;cursor: pointer;}' . "\r\n" . '	</style>' . "\r\n" . '<body>' . "\r\n" . '<div class="test"></div>' . "\r\n" . '	<div class="layer_iframe">' . "\r\n" . '		<div class="iframe_top"><span style="display:inline-block;width:20px;"></span>查看GPS轨迹<span class="close close_btn"><img alt="" src="./images/close.png"></span></div>' . "\r\n" . '		<div class="iframe_body map_body">' . "\r\n" . '			<div class="map_wrap" id="map_canvas"></div>' . "\r\n" . '			<div class="map_bottom">' . "\r\n" . '			<!-- <div class="map_position_tl">位置：</div>' . "\r\n" . '			<div id="map_lat_lng">东经---,北纬---</div> -->' . "\r\n" . '		</div>' . "\r\n" . '		</div>' . "\r\n" . '		<div class="iframe_foot"></div>' . "\r\n" . '	</div>' . "\r\n" . '</body>' . "\r\n" . '</html>' . "\r\n" . '' . "\r\n" . '<script language="javascript" src="';
echo Zhimin::g('assets_uri');
echo 'js/HCMap.js"></script>' . "\r\n" . '<script language="JavaScript" type="text/javascript">' . "\r\n" . '<!--' . "\r\n" . '' . "\r\n" . 'var t;' . "\r\n" . '' . "\r\n" . 'var CenterLat = ';
echo floatval($gpscenter['lat']);
echo ';//22.53126; //设置纬度' . "\r\n" . 'var CenterLng = ';
echo floatval($gpscenter['lng']);
echo ';//113.94250; //设置经度' . "\r\n" . '' . "\r\n" . '//定义全局的地图对象' . "\r\n" . 'var _MapMaplet = null;' . "\r\n" . '//定义全局的地图标记' . "\r\n" . 'var _marker = null;' . "\r\n" . 'var _latlngs = [];' . "\r\n" . '//视频播放时长' . "\r\n" . 'var _fTime = 0;' . "\r\n" . 'var _isMapLoaded = false;' . "\r\n" . '' . "\r\n" . 'function addLatLng(key){' . "\r\n" . '	//Lat = 0;//Lat + 0.01;' . "\r\n" . '	//Lng = 0;//Lng + 0.01;' . "\r\n" . '	if (!_isMapLoaded && _MapMaplet.isMapLoaded)' . "\r\n" . '	{' . "\r\n" . '		drawMarker();//0, 0, key);' . "\r\n" . '		_isMapLoaded = true;' . "\r\n" . '	}' . "\r\n" . '	' . "\r\n" . '	//t = setTimeout("addLatLng()", 1000);' . "\r\n" . '}' . "\r\n" . '// 初始化地图' . "\r\n" . 'function initMap(){' . "\r\n" . '	// 设置flash相对该页面的路径' . "\r\n" . '	$M.setSeverUrl("';
echo Zhimin::g('assets_uri');
echo 'js/AsMapForJs.swf");' . "\r\n" . '' . "\r\n" . '	var intMapZoom = 14; //设置地图放大级别' . "\r\n" . '	//var intMapWidth = document.documentElement.clientWidth; //设置宽度' . "\r\n" . '	//var intMapHeight = document.documentElement.clientHeight;//320; //设置高度' . "\r\n" . '	var intMapWidth =926; //设置宽度' . "\r\n" . '	var intMapHeight=519;' . "\r\n" . '' . "\r\n" . '	$M.setMapRoot(\'';
echo $gpservuri;
echo '\');' . "\r\n" . '	// 创建地图，并把返回的地图对象赋给_MapMaplet' . "\r\n" . '	_MapMaplet = $M.createMap("map_canvas", intMapWidth, intMapHeight, CenterLat, CenterLng, intMapZoom);' . "\r\n" . '	// 设置地图加载完成运行函数' . "\r\n" . '	_MapMaplet.setInitComplete(initMapComplete);' . "\r\n" . '};' . "\r\n" . '' . "\r\n" . 'function drawMarker(){//lat, lot, k) {' . "\r\n" . '	if(!_MapMaplet) return;' . "\r\n" . '' . "\r\n" . '	var gps_ = null;' . "\r\n" . '';

if (is_array($gps_data)) {
	$gps_ = '';

	foreach ($gps_data as $k => $gps ) {
		echo '	_latlngs.push({ lng: ' . $gps['lng'] . ', lat: ' . $gps['lat'] . ' });' . "\n" . '';
		$gps_ = '	gps_ = new Array(' . $gps['lat'] . ', ' . $gps['lng'] . ');' . "\n" . '';
	}

	if ($gps_ != '') {
		echo $gps_;
	}
}

echo '' . "\r\n" . '	if ( gps_ ) {' . "\r\n" . '		var lat = gps_[0];' . "\r\n" . '		var lng = gps_[1];' . "\r\n" . '		$(\'#map_lat_lng\').text("北纬 "+lat+",东经 "+lng);' . "\r\n" . '' . "\r\n" . '		var bChangeCenter = false;' . "\r\n" . '		var currentCenter = _MapMaplet.getCenter();' . "\r\n" . '		if ( Math.abs(lat - currentCenter.lat) > 0.0015) {' . "\r\n" . '			CenterLat = lat;' . "\r\n" . '			bChangeCenter = true;' . "\r\n" . '		}' . "\r\n" . '		if ( Math.abs(lng - currentCenter.lng) > 0.0015) {' . "\r\n" . '			CenterLng = lng;' . "\r\n" . '			bChangeCenter = true;' . "\r\n" . '		}' . "\r\n" . '		if ( bChangeCenter){' . "\r\n" . '			changeCenter( CenterLat, CenterLng);' . "\r\n" . '		}' . "\r\n" . '' . "\r\n" . '		if ( !window._PathGraphics) {' . "\r\n" . '			//画线' . "\r\n" . '	        window._PathGraphics = $M.createPathGraphics( _latlngs, "#ff0000", 3, 0.5 );' . "\r\n" . '	        _MapMaplet.addGraphics(window._PathGraphics);' . "\r\n" . '	        _MapMaplet.refreshGraphics();' . "\r\n" . '		} else {' . "\r\n" . '			//更新画线' . "\r\n" . '            window._PathGraphics.update( _latlngs );' . "\r\n" . '            _MapMaplet.refreshGraphics();' . "\r\n" . '		}' . "\r\n" . '		if ( !_marker) {' . "\r\n" . '			//创建文本标注' . "\r\n" . '			_marker = $M.createBalloonFalseMarker(lat, lng, "';
echo Zhimin::g('assets_uri');
echo 'img/poi.png", "当前位置: 北纬 "+lat+",东经 "+lng, parseInt(_MapMaplet.Width / 2), parseInt(_MapMaplet.Height / 2));    ' . "\r\n" . '			//地图对象添加标注' . "\r\n" . '			_MapMaplet.addMarker(_marker);' . "\r\n" . '			//在地图上显示添加的标注(默认刷新标注是显示的)' . "\r\n" . '			_MapMaplet.refreshMarkers();' . "\r\n" . '			//显示标注' . "\r\n" . '			//_marker.show();' . "\r\n" . '		} else {' . "\r\n" . '			_marker.updateMarker(lat, lng);' . "\r\n" . '            _marker.refresh();' . "\r\n" . '		}' . "\r\n" . '	}' . "\r\n" . '	' . "\r\n" . '}' . "\r\n" . '' . "\r\n" . 'function changeCenter(lat, lot) {' . "\r\n" . '	if(!_MapMaplet) return;' . "\r\n" . '	//设置地图中心点' . "\r\n" . '    _MapMaplet.setCenter(lat, lot);' . "\r\n" . '	//map.moveToCenter(new LTPoint(lot * 100000 + 504 , lat * 100000 - 290 ));' . "\r\n" . '}' . "\r\n" . '' . "\r\n" . 'function initMapComplete(){' . "\r\n" . '	 // 创建工具管理对象' . "\r\n" . '	_MapToolManager = $M.createToolManager();' . "\r\n" . '	_MapMaplet.addToolManager(_MapToolManager);' . "\r\n" . '	// 地图鹰眼图工具' . "\r\n" . '	_MapToolManager.addEagleMap();' . "\r\n" . '	// 地图等级滚动条工具' . "\r\n" . '    _MapToolManager.addBlueZoomBar();' . "\r\n" . '    ' . "\r\n" . '	t = setTimeout("addLatLng()", 1000);' . "\r\n" . '};' . "\r\n" . '' . "\r\n" . 'initMap();' . "\r\n" . '' . "\r\n" . '$(\'#map_lat_lng\').click(function(){' . "\r\n" . '	//获取当前地图中心点' . "\r\n" . '    var currentCenter = _MapMaplet.getCenter();' . "\r\n" . '	//$(\'#map_lat_lng\').text($(\'#map_lat_lng\').text() + currentCenter.lat + \' \' + currentCenter.lng);' . "\r\n" . '	$(\'#map_lat_lng\').text( "当前位置: 北纬 "+currentCenter.lat + \', 东经\' + currentCenter.lng);' . "\r\n" . '});' . "\r\n" . '' . "\r\n" . '//-->' . "\r\n" . '</script>';

?>
