<?php

echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">' . "\r\n" . '<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">' . "\r\n" . '<head>' . "\r\n" . '    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">' . "\r\n" . '    <title>用户编辑页</title>' . "\r\n" . '    <script type="text/javascript" src="';
echo Zhimin::g('assets_uri');
echo 'js/jquery.min.js"></script>' . "\r\n" . '    <script type="text/javascript" src="';
echo Zhimin::g('assets_uri');
echo 'js/laydate/laydate.js"></script>' . "\r\n" . '    <script type="text/javascript" src="';
echo Zhimin::g('assets_uri');
echo 'js/layer/layer.js"></script>' . "\r\n" . '    <script type="text/javascript" src="';
echo Zhimin::g('assets_uri');
echo 'js/global.js"></script>' . "\r\n" . '    <script type="text/javascript" src="';
echo Zhimin::g('assets_uri');
echo 'js/userEdit.js"></script>' . "\r\n" . '    <link rel="stylesheet" type="text/css" href="';
echo Zhimin::g('assets_uri');
echo 'style/reset.css" />' . "\r\n" . '    <link rel="stylesheet" type="text/css" href="';
echo Zhimin::g('assets_uri');
echo 'style/global.css" />' . "\r\n" . '    <link rel="stylesheet" type="text/css" href="';
echo Zhimin::g('assets_uri');
echo 'js/themes/default/easyui.css">' . "\r\n" . '	<link rel="stylesheet" type="text/css" href="';
echo Zhimin::g('assets_uri');
echo 'js/themes/icon.css">' . "\r\n" . '	<link rel="stylesheet" type="text/css" href="';
echo Zhimin::g('assets_uri');
echo 'style/re_easyui.css">' . "\r\n" . '	<script type="text/javascript" src="';
echo Zhimin::g('assets_uri');
echo 'js/jquery.easyui.min.js"></script>' . "\r\n" . '    <!--[if IE 7]>' . "\r\n" . '<style>' . "\r\n" . '.notice_top .close{position: absolute;top:18px;right:18px;float: right;margin-right:0; margin-top:0;display: inline-block;}' . "\r\n" . '.atten_top .close{line-height: normal;}' . "\r\n" . '</style>' . "\r\n" . '<![endif]-->' . "\r\n" . '' . "\r\n" . '<body>' . "\r\n" . '<div class="layer_iframe1">' . "\r\n" . '    <div class="iframe_top1">编辑<span class="close1 close_btn"><img src="./images/close.png" alt="" /></span></div>' . "\r\n" . '    <div class="iframe_body1">' . "\r\n" . '        <form action="';
echo Zhimin::buildUrl();
echo '&action=edit" method="post" name="user_edit_form" id="user_edit_form">' . "\r\n" . '            <div class="con_atten_wrap recorder_notice">' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '                    <div class="condition_345 condition_s">' . "\r\n" . '                        <span class="condition_title">用户名：</span>' . "\r\n" . '                         <font class="sign_d sign_star1">*</font>' . "\r\n" . '                        <div class="select_260 select_div select_relative select_in selec_text">' . "\r\n" . '                            <p>';
echo $data['username'];
echo '</p>' . "\r\n" . '                        </div>' . "\r\n" . '                    </div>' . "\r\n" . '                    <div class="clear"></div>' . "\r\n" . '                </div>' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '                    <div class="condition_345 condition_s">' . "\r\n" . '                        <span class="condition_title">' . $_SESSION['zfz_type'] . '姓名：</span>' . "\r\n" . '                        <font class="sign_d sign_star">*</font>' . "\r\n" . '                        <div class="select_260 select_div select_relative select_in">' . "\r\n" . '                            <input type="text" class="input_error input_error1" name="realname" value="';
echo $data['realname'];
echo '" />' . "\r\n" . '                            <span class="error_msg">请选填写' . $_SESSION['zfz_type'] . '姓名</span>' . "\r\n" . '                        </div>' . "\r\n" . '                    </div>' . "\r\n" . '                    <div class="clear"></div>' . "\r\n" . '                </div>' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '                    <div class="condition_345 condition_s">' . "\r\n" . '                        <span class="condition_title">' . $_SESSION['zfz_type'] . '编号：</span>' . "\r\n" . '                         <font class="sign_d sign_star1">*</font>' . "\r\n" . '                        <div class="select_260 select_div select_relative select_in">' . "\r\n" . '                            <input type="text" class="input_error1" name="hostcode" value="';
echo $data['hostcode'];
echo '" />' . "\r\n" . '                            <span class="error_msg">请选填写' . $_SESSION['zfz_type'] . '编号</span>' . "\r\n" . '                        </div>' . "\r\n" . '                    </div>' . "\r\n" . '                    <div class="clear"></div>' . "\r\n" . '                </div>' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '                    <div class="condition_345 condition_s">' . "\r\n" . '                        <span class="condition_title">单位：</span>' . "\r\n" . '                        <font class="sign_d sign_star">*</font>' . "\r\n" . '                        <div class="select_260 select_div">' . "\r\n" . '                        	<input class="easyui-combotree" name="danwei_edit" data-options="" style="width:100%;" id="easyui_edit"/>' . "\r\n" . '                            ' . "\r\n" . '                        </div>' . "\r\n" . '                    </div>' . "\r\n" . '                    <div class="clear"></div>' . "\r\n" . '                </div>' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '                    <div class="condition_345 condition_s">' . "\r\n" . '                        <span class="condition_title">角色：</span>' . "\r\n" . '                        <font class="sign_d sign_star">*</font>' . "\r\n" . '                        <div class="select_260 select_div">' . "\r\n" . '                        	<select class="easy_u" name="group" style="width:100%;">' . "\r\n" . '								<option value="">-请选择-</option>' . "\r\n" . '								';

foreach ($user_groups as $k => $v ) {
	echo '<option value="' . $v['bh'] . '"';
	echo '>' . $v['gname'] . '</option>';
}

echo '							</select>' . "\r\n" . '                    	</div>' . "\r\n" . '                     </div>' . "\r\n" . '                    <div class="clear"></div>' . "\r\n" . '                </div>' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '					<div class="condition_345 condition_s">' . "\r\n" . '						<span class="condition_title">排序：</span>' . "\r\n" . '                        <font class="sign_d sign_star1">*</font>' . "\r\n" . '						<div class="select_260 select_div select_in select_config">	' . "\r\n" . '							<input type="text" name="sort" value="';
echo $data['sort'] == '' ? 1 : $data['sort'];
echo '" />' . "\r\n" . '							<div class="sign">' . "\r\n" . '								<span class="plus"></span>' . "\r\n" . '								<span class="minus"></span>' . "\r\n" . '							</div>' . "\r\n" . '						</div>' . "\r\n" . '					</div>' . "\r\n" . '					<div class="clear"></div>' . "\r\n" . '				</div>' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '                    <div class="clear"></div>' . "\r\n" . '                </div>' . "\r\n" . '                <div class="condition_top">' . "\r\n" . '                    <div class="condition_345 condition_s ">' . "\r\n" . '                        <font class="sign_d sign_star1">*</font>' . "\r\n" . '                        <div class="select_260 select_div select_in selec_text">' . "\r\n" . '                        	<input type="hidden" name="saveflag" value="1" />' . "\r\n" . '                        	<input type="hidden" name="id" value="';
echo $data['id'];
echo '" />' . "\r\n" . '                            <span class="sure_add" id="edit_submit">确 定</span>' . "\r\n" . '                            <span class="sure_cancle close_btn">取 消</span>' . "\r\n" . '                        </div>' . "\r\n" . '                    </div>' . "\r\n" . '                    <div class="clear"></div>' . "\r\n" . '                </div>' . "\r\n" . '            </div>' . "\r\n" . '        </form>' . "\r\n" . '    </div>' . "\r\n" . '    <div class="iframe_foot1"></div>' . "\r\n" . '</div>' . "\r\n" . '<!-- 成功提示框 -->' . "\r\n" . '<div class="layer_notice lay_success">' . "\r\n" . '    <div class="notice_top"><span class="close close_btn">X</span></div>' . "\r\n" . '    <div class="notice_body">' . "\r\n" . '        <div class="n_left">' . "\r\n" . '            <img src="./images/success_bg.png">' . "\r\n" . '        </div>' . "\r\n" . '        <div class="n_right">' . "\r\n" . '            <p id="success_flg">编辑成功......<font>3</font>秒钟后返回页面！</p>' . "\r\n" . '            <div class="clear"></div>' . "\r\n" . '            <span class="cancle_span close_btn">确 定</span>' . "\r\n" . '        </div>' . "\r\n" . '    </div>' . "\r\n" . '    <div class="notice_foot"></div>' . "\r\n" . '</div>' . "\r\n" . '<!-- 失败提示框 -->' . "\r\n" . '<div class="layer_notice lay_wrong">' . "\r\n" . '    <div class="notice_top"><span class="close close_btn">X</span></div>' . "\r\n" . '    <div class="notice_body">' . "\r\n" . '        <div class="n_left">' . "\r\n" . '            <img src="./images/notice_bg.png">' . "\r\n" . '        </div>' . "\r\n" . '        <div class="n_right">' . "\r\n" . '            <p id="fail_flg">编辑失败......<font>3</font>秒钟后返回页面！</p>' . "\r\n" . '            <div class="clear"></div>' . "\r\n" . '            <span class="cancle_span close_btn_self">确 定</span>' . "\r\n" . '        </div>' . "\r\n" . '    </div>' . "\r\n" . '    <div class="notice_foot"></div>' . "\r\n" . '</div>' . "\r\n" . '<script type="text/javascript">' . "\r\n" . '$(document).ready(function(){' . "\r\n" . '	/*edit tree*/' . "\r\n" . '	$("#easyui_edit").combotree({url:\'';
echo Zhimin::buildUrl('unitjson', 'other') . '&id=bh&text=dname';
echo '\',method:\'get\',labelPosition:\'top\',panelWidth:\'500px\',' . "\r\n" . '	// 设置选中项' . "\r\n" . '	onLoadSuccess:function(node,data){' . "\r\n" . '		$("#easyui_edit").combotree(\'setValues\', [\'\']);  ' . "\r\n" . '    }  ' . "\r\n" . '	});/*add tree end*/' . "\r\n" . '	$(\'.easy_u\').combobox({panelHeight:\'120px\',selectOnNavigation:true,editable:false,labelPosition:\'top\'});' . "\r\n" . '	' . "\r\n" . '})' . "\r\n" . '</script>' . "\r\n" . '</body>' . "\r\n" . '</html>';

?>
